//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bars
    {
        public int BarID { get; set; }
        public string BarName { get; set; }
        public string City { get; set; }
        public int Reviews { get; set; }
    }
}
